development:
  database: UTF
  adapter: sqlserver
  encoding: utf8
  username: sa
  password: utf@123456
  host: ec2-3-20-174-194.us-east-2.compute.amazonaws.com
  port: 1433

development_sec:
  adapter: mysql2
  database: utrade_prod
  pool: 5
  username: root
  password: root
  host: ec2-3-14-64-102.us-east-2.compute.amazonaws.com
  port: 3306 